### ISSUE TITLE
posgtgres user password for ohdsi chart

### ISSUE THREAD

**Issue by ssaranathan** [chgl/charts#50]
Hi @chgl ,
I was able to install both Atlas and WebAPI using a Postgres DB that I had provisioned outside of the chart.

Now, I am back to trying it via the chart.

I see that the postgesql pod and service are getting created.  I am trying to to go into the pod and see the tables that have been created.  I tried to do psql -U postgres

None of the passwords listed in the auto created secret(ohdsi-postgresql ) works
 (postgresql-password: xxx==
  postgresql-postgres-password: yyy==)

WebAPI is also not able to authenticate with the password defined in the secret.

Any idea what is missing ?
Thanks again for your tips and help.

**Comment by chgl** [comment]
By default the passwords inside the secret are base64-encoded, so you'll need to decode them before being able to use the actual password, ie:

```sh
echo -n "yyy==" | base64 -d
```

One challenging thing of the Bitnami postgres chart is that it creates a random password by default, which is updated whenever you upgrade the chart, see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#upgrading. Setting `postgresqlPostgresPassword` and/or `postgresqlPassword` to a fixed value or using `existingSecret` (see https://github.com/bitnami/charts/tree/master/bitnami/postgresql#parameters) should prevent this. Let me know if this helped 🤞!

**Comment by ssaranathan** [comment]
Thanks @chgl .

Tried with removing my secret and let bitnami installation to create its own secret.  So based on the comment you had in webapi.db section,
`# the database password. 
Only used if postgresql.enabled=false, otherwise the secret created by the postgresql chart is used`
I did not put any password in that column in webapi.db.  But WebAPI is not able to connect to postgres and I see that error in the logs.   So WebAPI is not coming up.

I tried with my own secret (password is a plain text without encoding) and WebAPI.db section has the same plain text as password, WebAPI is able to connect to PostgresDB.  But I when I use the same password ( both plain text as in the secret or encoded from https://www.base64encode.org/) in psql -U, I am not able to connect to PostgresDB.  

If I use a encoded text in the secret ( https://www.base64encode.org/),  WebAPI is unable to connect to Postgres using both the encoded and decoded text for webapi.db.password.

Something is missing.

**Comment by chgl** [comment]
Here's how I got the DB's password when installing via the included chart:

```sh
helm install ohdsi chgl/ohdsi

# note the inclusion of base64 -d at the end
# you should be able to use the name of your custom secret instead of "ohdsi-postgresql" here:
$ kubectl get secrets/ohdsi-postgresql --template="{{ index .data \"postgresql-password\" }}" | base64 -d
3ZDadyaOEE

kubectl port-forward service/ohdsi-postgresql 5432:5432

# in a new terminal
$ PGHOST=localhost PGUSER=postgres PGPASSWORD=3ZDadyaOEE psql
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------+----------+----------+-------------+-------------+-----------------------
 ohdsi     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(4 rows)

postgres=# \c ohdsi
You are now connected to database "ohdsi" as user "postgres".

ohdsi=# \dn
  List of schemas
  Name  |  Owner
--------+----------
 ohdsi  | postgres
 public | postgres
(2 rows)

ohdsi=# \dt *.*
                           List of relations
       Schema       |             Name              | Type  |  Owner
--------------------+-------------------------------+-------+----------
 information_schema | sql_features                  | table | postgres
 information_schema | sql_implementation_info       | table | postgres
 information_schema | sql_parts                     | table | postgres
 information_schema | sql_sizing                    | table | postgres
 ohdsi              | analysis_generation_info      | table | postgres
 ohdsi              | batch_job_execution           | table | postgres
 ohdsi              | batch_job_execution_context   | table | postgres
 ohdsi              | batch_job_execution_params    | table | postgres
 ohdsi              | batch_job_instance            | table | postgres
 ohdsi              | batch_step_execution          | table | postgres
 ohdsi              | batch_step_execution_context  | table | postgres
 ohdsi              | cc_analysis                   | table | postgres
 ohdsi              | cc_cohort                     | table | postgres
 ohdsi              | cc_param                      | table | postgres
 ohdsi              | cc_strata                     | table | postgres
 ohdsi              | cc_strata_conceptset          | table | postgres
 ohdsi              | cca                           | table | postgres
 ohdsi              | cca_execution                 | table | postgres
# ...
```

Let me know if this helps!

**Comment by ssaranathan** [comment]
Awesome..  Thanks @chgl .  Though the 
`kubectl get secrets/ohdsi-postgresql --template="{{ index .data \"postgresql-password\" }}" | base64 -d`

gave me an error, 
`error: error parsing template {{ index .data \postgresql-password\ }}, template: output:1: unexpected "\\" in operand`
 
I was able to get the string from :https://www.base64decode.org/

Thanks for your help and I will close this issue.

**Comment by chgl** [comment]
Great! Glad it works!
