### ISSUE TITLE
Parsing error in ohdsi - postgresql chart

### ISSUE THREAD

**Issue by ssaranathan** [chgl/charts#63]
Hi @chgl ,
I tried to pull the latest chart and deploy.  I get this error message:
`Error: parse error at (ohdsi/charts/postgresql/charts/common/templates/_secrets.tpl:84): function "lookup" not defined`

**Comment by chgl** [comment]
What version of the helm CLI are you using? I think you should be able to resolve this by updating to a recent version (https://github.com/helm/helm/issues/7955)

**Comment by ssaranathan** [comment]
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}

**Comment by chgl** [comment]
Oh that's definitely a bit old. Please try updating to the latest version if possible: https://github.com/helm/helm/releases/tag/v3.5.3

**Comment by ssaranathan** [comment]
Thanks @chgl .  Helm update fixed it. Appreciate your quick responses.
